# Generated by Django 3.2.6 on 2021-08-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='vsrank',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='wlecomeofferrank',
            field=models.IntegerField(unique=True),
        ),
    ]
