# Generated by Django 3.2.6 on 2021-08-05 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210805_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='logolink',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
