# Generated by Django 3.2.6 on 2021-08-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_books_logolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='BonusCode',
            field=models.CharField(default='VEGAS SPORTS', max_length=30),
        ),
    ]
