# Generated by Django 3.2.6 on 2021-08-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_books_bonuscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='appstorerateing',
            field=models.FloatField(default=3.0),
        ),
    ]
