# Generated by Django 3.2.6 on 2021-08-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_books_appstorerateing'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Deposit',
            field=models.CharField(default='VISA, MC, PayPal, VIPpreferred, Play+, Discover, Online Banking', max_length=100),
        ),
    ]
