# Generated by Django 3.2.6 on 2021-08-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_books_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='statecode',
            field=models.CharField(default='NULL', max_length=3),
        ),
    ]
